CREATE USER @DB_USER@ IDENTIFIED BY @DB_PASSWORD@ DEFAULT TABLESPACE @TABLESPACE@ TEMPORARY TABLESPACE @TEMP_TABLESPACE@;
GRANT ADMINISTER SQL TUNING SET TO @DB_USER@;
GRANT ADVISOR TO @DB_USER@;
GRANT UNLIMITED TABLESPACE TO @DB_USER@;
GRANT "CONNECT" TO @DB_USER@;
GRANT "RESOURCE" TO @DB_USER@;
GRANT "SELECT_CATALOG_ROLE" TO @DB_USER@;
ALTER USER @DB_USER@ DEFAULT ROLE ALL;
